### ISSUE TITLE
FNet doesn't compile

### ISSUE THREAD

**Issue by luni64** [luni64/VisualTeensy#53]
Copied from: https://forum.pjrc.com/threads/66318-Visualteensy-amp-Teensyduino-1-54-beta-6-issue-with-multiple-definitions?p=285522&viewfull=1#post285522

@luni, I'm seeing this issue again (had forgotten about it, and mentioned it in the Teensyduino 1.54 Released thread). All I have to do is update FNET from 4.6.3 to 4.7.0 (or 4.7.1) to see errors, multiple definition of `fnet_mimxrt_serial_init' and others.

Saw this on 2 separate Win 10 PCs. Fresh install of Arduino, Teensyduino 1.54 and VisualTeensy v1.0.0.0 (or v0.9.9.3).

Code compiles with regular Arduino 1.8.15

To recreate:

1. New Visualteensy project
2. Add SPI (v1.0), FNET (v0.1.3) & NativeEthernet (v1.0.5) libs (from Teensyduino) to VisualTeensy
3. Add this code: https://raw.githubusercontent.com/vj...pNtpClient.ino
4. Comment out the error in loop or move loop to bottom of file
5. Save, opens in VSCode
6. Build and see error

Teensy 4.1

Thanks

**Comment by luni64** [comment]
Here a version which should fix that. Can you give it a try?
[VisualTeensy_v1_0_0_0.zip](https://github.com/luni64/VisualTeensy/files/6949514/VisualTeensy_v1_0_0_0.zip)
